export const screenName = {
  Home: 'Home',
  Bag: 'Bag',
  OrderSummary: 'OrderSummary',
  Payment: 'Payment',
  PaymentMethod: 'PaymentMethod',
  PaymentMethod1: 'PaymentMethod1',
  OrderSuccess: 'OrderSuccess',
  OrderHistory: 'OrderHistory',
  StartYourOrder: 'StartYourOrder',
  ChooseLocation: 'ChooseLocation',
  Profile: 'Profile',
  FavoriteRestaurantScreen: 'FavoriteRestaurantScreen',
  Drawer: 'Drawer',
  Menu: 'Menu',
  OrderDetailPage: 'OrderDetailPage',
  OrderCheckout: 'OrderCheckout',
  AllRestaurants: 'AllRestaurants',
  GroceriesScreen: 'GroceriesScreen',
};
